name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: dicomviewer

jobs:
  oci:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        databases: ['oci']
        server-versions: ['stable21']

    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    services:
      oracle:
        image: deepdiver/docker-oracle-xe-11g # "wnameless/oracle-xe-11g-r2"
        ports:
          - "1521:1521"

    steps:
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up PHPUnit and Build
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i && make

      - name: Set up php ${{ matrix.php-versions }}
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: mbstring, iconv, fileinfo, intl, oci8
          tools: phpunit:8.5.2
          coverage: none

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php -f index.php
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: PHPUnit
        working-directory: apps/${{ env.APP_NAME }}/tests
        run: phpunit -c phpunit.xml
