name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

env:
  APP_NAME: dicomviewer

jobs:
  oci:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.2']
        databases: ['oci']
        server-versions: ['stable29']

    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}

    services:
      oracle:
        image: ghcr.io/gvenzl/oracle-xe:11

        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: autotest
          APP_USER_PASSWORD: owncloud

        # Forward Oracle port
        ports:
          - 1521:1521/tcp

        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout server
        uses: actions/checkout@v4
        with:
          repository: nextcloud/server
          submodules: 'recursive'
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: apps/${{ env.APP_NAME }}

      - name: Build
        working-directory: apps/${{ env.APP_NAME }}
        run: make

      - name: Set up php ${{ matrix.php-versions }}
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: mbstring, iconv, fileinfo, intl, oci8
          tools: phpunit
          coverage: none

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php -f index.php
          ./occ app:enable --force ${{ env.APP_NAME }}
